# Generated by Django 3.2.20 on 2023-07-14 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('meal_type', models.IntegerField(choices=[(0, 'Breakfast'), (1, 'Lunch'), (2, 'Dinner'), (3, 'Dessert'), (4, 'Snack')], default=0)),
                ('preptime_in_minutes', models.DecimalField(decimal_places=1, max_digits=3)),
                ('calories_in_grams', models.DecimalField(decimal_places=1, max_digits=5)),
                ('protein_in_grams', models.DecimalField(decimal_places=1, max_digits=4)),
                ('fat_in_grams', models.DecimalField(decimal_places=1, max_digits=4)),
                ('carbs_in_grams', models.DecimalField(decimal_places=1, max_digits=4)),
                ('recipe', models.TextField(default='This recipe has not been added yet!')),
            ],
        ),
    ]
