# Generated by Django 3.2.20 on 2023-07-17 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealpin', '0002_mymeals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='calories_in_grams',
            field=models.DecimalField(decimal_places=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='meal',
            name='preptime_in_minutes',
            field=models.DecimalField(decimal_places=0, max_digits=3),
        ),
    ]
